<?php

/**
 * @file
 * Contains omise_payment.module..
 */

use Drupal\omise_payment\Entity\OmiseCustomer;;

/**
 * Implements hook_page_top().
 */
function omise_payment_page_top(array &$page_top)
{

    // Add Omise checkout form to all pages
    // @TODO - add it only when an Omise field is loaded
    $page_top['omise_payment'] = \Drupal::formBuilder()->getForm('\Drupal\omise_payment\Form\CheckoutCollectCardForm');
}

/**
 * Implements hook_theme()
 * @param array $existing
 * @param $type
 * @param $theme
 * @param $path
 * @return array
 */
function omise_payment_theme(array $existing, $type, $theme, $path)
{
    return [
        'omise_cards_list' => [
            'variables' => [
                'cards' => null,
                'modulePath' => null,
                'drupalOmiseCustomer' => null
            ]
        ],
        'omise_bank_account' => [
            'variables' => [
                'bankAccount' => null
            ]
        ],
    ];
}

/**
 * Implements hook_entity_insert
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function omise_payment_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
    if ($entity->bundle()=="user" &&
    $entity->get('field_credit_card') &&
        $entity->get('field_credit_card')->target_id) {
        // Set uid on customer id if is set the field
        $drupalOmiseCustomer = OmiseCustomer::load($entity->get('field_credit_card')->target_id);
        $drupalOmiseCustomer->set('user_id',$entity->id());
        $drupalOmiseCustomer->save();
    }
}
