bcct_payments:
  charge_type: recurring
  recurring_period: monthly
  amount: 0
  signup_amount: 0
  currency: THB
_core:
  default_config_hash: tDbbg3DELmk5WjgBBKqUX14Yy8Lu00noYLsJ5CUjPxs
charge_type: on_creation
recurring_period: monthly
amount: '800'
signup_amount: ''
currency: THB
